Clean up old kernel sources in /usr/src for gentoo-update-kernel
Also include pipx packages in system udpate

diff --git a/bash/gentoo/gentoo-update-kernel b/bash/gentoo/gentoo-update-kernel
--- a/bash/gentoo/gentoo-update-kernel
+++ b/bash/gentoo/gentoo-update-kernel
@@ -1,32 +1,50 @@
 #!/usr/bin/env bash
 
-# NOTE: Intended for my personal use, has not been tested on any machines but my own
-#       Use at your own risk!
-
 function log {
   echo "$@" 1>&2
+}
+
+function deletion-candidates {
+  local _path="$1"
+  sudo ls "$1" \
+    | grep -vP "(linux|$(uname -r)|$(eselect kernel list | awk '{print $2}' | tail -n+2 | sed -r 's/linux-//' | paste -sd'|'))"
 }
 
 bootloader_path="/boot/efi/$(</etc/machine-id)"
 # Only clean kernels that are no longer installed
 # Explicitly exclude currently running system just in case
-deletion_list="$(sudo ls "$bootloader_path" \
-  | grep -vP "($(uname -r)|$(eselect kernel list | awk '{print $2}' | tail -n+2 | sed -r 's/linux-//' | paste -sd'|'))")"
+#deletion_list="$(sudo ls "$bootloader_path" \
+  #| grep -vP "($(uname -r)|$(eselect kernel list | awk '{print $2}' | tail -n+2 | sed -r 's/linux-//' | paste -sd'|'))")"
+efi_deletion_list="$(deletion-candidates "$bootloader_path")"
+src_deletion_list="$(deletion-candidates /usr/src)"
 
 set -eo pipefail
 
-# My /boot/efi partition was set a bit too small, so I need to cleanup old kernels every time
-if [[ -z "$deletion_list" ]]; then
+if [[ -z "$efi_deletion_list" ]]; then
   log "No old kernels in /boot/efi to cleanup"
 else
-  log -e "Cleanup old kernels from /boot/efi:\n${deletion_list}"
+  log "Running kernel: $(uname -r)"
+  log -e "Cleanup old kernels from /boot/efi:\n${efi_deletion_list}"
   read -n1 -p "Confirm? Y/n" confirm
   if [[ "$confirm" == 'n' ]]; then
     log "Aborting!"
     exit 1
   fi
-  #log "sudo rm -r ${deletion_list}"
-  sudo rm -r "${bootloader_path}/${deletion_list}"
+  sudo rm -r "${bootloader_path}/${efi_deletion_list}"
+fi
+
+# TODO: Combine with efi cleanup?
+if [[ -z "$src_deletion_list" ]]; then
+  log "No old kernels in /usr/src to cleanup"
+else
+  log "Running kernel: $(uname -r)"
+  log -e "Cleanup old kernel sources from /usr/src:\n${src_deletion_list}"
+  read -n1 -p "Confirm? Y/n" confirm
+  if [[ "$confirm" == 'n' ]]; then
+    log "Aborting!"
+    exit 1
+  fi
+  sudo rm -r "/usr/src/${src_deletion_list}"
 fi
 
 kernel_select="$(eselect kernel list | fzf --print-query -0 | head -n1)"
@@ -40,5 +58,3 @@ log "Upgrading kernel and modules"
 #log "sudo eselect kernel $kernel_select" && exit 0
 sudo eselect kernel set "$kernel_select"
 sudo bash -c 'cd /usr/src/linux && make -j12 && emerge -v @module-rebuild && make modules_install && make install'
-
-# TODO: figure out how to automatically set the new kernel as default in systemd-bootloader when updated
